# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
workspace 'MVPTest'

def rxPods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
end



target 'MVPTest' do
  rxPods
  
  target 'Services' do
    inherit! :search_paths
    project 'Services/Services.project'
  end
  
  target 'Core' do
    inherit! :search_paths
    project 'Core/Core.project'
  end
  
  target 'PlayerList' do
    inherit! :search_paths
    project 'PlayerList/PlayerList.project'
  end
  
  target 'PlayerDetail' do
    inherit! :search_paths
    project 'PlayerDetail/PlayerDetail.project'
  end
end

###### Post install configs ######
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
